### POST register
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "email": "beak@gmail.com",
    "username": "pipiipii",
    "password": "1612321545456"
}


### POST login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "test88@gmail.com",
    "password": "test888123"
}


