### POST
POST http://localhost:3000/api/v1/customers/customer
Content-Type: application/json

### GET
GET http://localhost:3000/api/v1/customers/customer/me
Content-Type:  application/json

### GET
GET http://localhost:3000/api/v1/customers/customers/:id
Content-Type: application/json