### POST //เส้นนี้ผ่่านแล้ว แต่ยังสร้างซ้ำ
POST http://localhost:3000/api/v1/customers
Content-Type: application/json

                    {
                    "guardian": {
                        "firstName": "เอวา",
                        "lastName": "ทรงเสรี",
                        "relationship": "บุตรสาว",
                        "phone": "0854252541",
                        "email": "eva.songseree@example.com"
                    },
                    "seniors": [
                    "65a02001f1a2b3c4d5e6f401"
                    ],
                    "userID": "65a00001f1a2b3c4d5e6f202",
                    "firstName": "นิรันดร์",
                    "lastName": "สุขสันต์",
                    "gender": "Male",
                    "dob": "1990-05-15",
                    "phone": "0854252541",
                    "address": "123 ถนนสุขุมวิท แขวงคลองตัน เขตคลองเตย กรุงเทพฯ 10110"
                    }

### GET
GET http://localhost:3000/api/v1/clients/client/me
Content-Type:  application/json

### GET //เส้นนี้ผ่่านแล้ว
GET http://localhost:3000/api/v1/customers/65a02001f1a2b3c4d5e6f401
Content-Type: application/json

### GET customer by userID
GET http://localhost:3000/api/v1/customers/user/65a00001f1a2b3c4d5e6f101
