###
GET  http://localhost:3000/api/mock/services
Content-Type: application/json

###
POST http://localhost:3000/api/mock/createService
Content-Type:  application/json

        {
            "name": "ป๋าหนุน",
            "description": "รักษาตลอดชีพ",
            "price": "2500"
        }