### GET
GET http://localhost:3000/api/v1/packages/packageslist
Content-Type: application/json

### GET
GET http://localhost:3000/api/v1/packages/packageslist/659e1001f1a2b3c4d5e6f001
Content-Type: application/json